# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Dev branch CI 
# Runs CI on all libraries when a PR is merged to dev

on:
  push:
    branches:
      - "dev"

concurrency:
  group: dev-ci-${{github.ref}}
  cancel-in-progress: true

jobs:
  build-test:
    runs-on: ubuntu-latest

    strategy:
        fail-fast: false
        matrix:
          library: 
            - msal-core
            - msal-common
            - msal-browser
            - msal-node
            - msal-angular
            - msal-react

    name: ${{ matrix.library }}
  
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2

    - name: Restore node_modules
      uses: actions/cache@v2
      id: cache
      with:
        path: |
          node_modules
          lib/*/node_modules
        key: ${{ runner.os }}-${{ hashFiles('package-lock.json', 'lib/*/package-lock.json') }}

    - name: Clean Install
      if: steps.cache.outputs.cache-hit != 'true'
      env:
        RUNNING_NODE_CI: 1
      run: npm ci

    - name: Build packages
      working-directory: lib/${{ matrix.library }}
      run: npm run build:all

    - name: Unit Tests with coverage
      working-directory: lib/${{ matrix.library }}
      run: npm run test:coverage

    - name: Upload Test Coverage to CodeCov
      if: success()
      uses: codecov/codecov-action@v1
      with:
        files: lib/${{matrix.library}}/coverage/lcov.info
        flags: ${{ matrix.library }}
        root_dir: lib/${{ matrix.library }}
        gcov_prefix: lib/${{ matrix.library }}
